// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.grpc.stubs;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Empty)
    com.google.protobuf.MessageOrBuilder {
}
