// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.grpc.stubs;

public interface GuestListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GuestList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Guest guests = 1;</code>
   */
  java.util.List<com.grpc.stubs.Guest> 
      getGuestsList();
  /**
   * <code>repeated .Guest guests = 1;</code>
   */
  com.grpc.stubs.Guest getGuests(int index);
  /**
   * <code>repeated .Guest guests = 1;</code>
   */
  int getGuestsCount();
  /**
   * <code>repeated .Guest guests = 1;</code>
   */
  java.util.List<? extends com.grpc.stubs.GuestOrBuilder> 
      getGuestsOrBuilderList();
  /**
   * <code>repeated .Guest guests = 1;</code>
   */
  com.grpc.stubs.GuestOrBuilder getGuestsOrBuilder(
      int index);
}
