// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.grpc.stubs;

public final class Hotel {
  private Hotel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Guest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Guest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetGuestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetGuestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateGuestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateGuestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateGuestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateGuestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteGuestRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteGuestRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GuestList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GuestList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Reservation_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Reservation_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteReservationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteReservationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ReservationList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ReservationList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Room_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Room_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UpdateRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_UpdateRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DeleteRoomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DeleteRoomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_RoomList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_RoomList_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013hotel.proto\"_\n\005Guest\022\n\n\002id\030\001 \001(\005\022\022\n\nfi" +
      "rst_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\r\n\005ema" +
      "il\030\004 \001(\t\022\024\n\014phone_number\030\005 \001(\t\"\035\n\017GetGue" +
      "stRequest\022\n\n\002id\030\001 \001(\005\"`\n\022CreateGuestRequ" +
      "est\022\022\n\nfirst_name\030\001 \001(\t\022\021\n\tlast_name\030\002 \001" +
      "(\t\022\r\n\005email\030\003 \001(\t\022\024\n\014phone_number\030\004 \001(\t\"" +
      "l\n\022UpdateGuestRequest\022\n\n\002id\030\001 \001(\005\022\022\n\nfir" +
      "st_name\030\002 \001(\t\022\021\n\tlast_name\030\003 \001(\t\022\r\n\005emai" +
      "l\030\004 \001(\t\022\024\n\014phone_number\030\005 \001(\t\" \n\022DeleteG" +
      "uestRequest\022\n\n\002id\030\001 \001(\005\"#\n\tGuestList\022\026\n\006" +
      "guests\030\001 \003(\0132\006.Guest\"\177\n\013Reservation\022\n\n\002i" +
      "d\030\001 \001(\005\022\025\n\rcheck_in_date\030\002 \001(\t\022\026\n\016check_" +
      "out_date\030\003 \001(\t\022\022\n\ntotal_cost\030\004 \001(\002\022\020\n\010gu" +
      "est_id\030\005 \001(\005\022\017\n\007room_id\030\006 \001(\005\"#\n\025GetRese" +
      "rvationRequest\022\n\n\002id\030\001 \001(\005\"\200\001\n\030CreateRes" +
      "ervationRequest\022\025\n\rcheck_in_date\030\001 \001(\t\022\026" +
      "\n\016check_out_date\030\002 \001(\t\022\022\n\ntotal_cost\030\003 \001" +
      "(\002\022\020\n\010guest_id\030\004 \001(\005\022\017\n\007room_id\030\005 \001(\005\"\214\001" +
      "\n\030UpdateReservationRequest\022\n\n\002id\030\001 \001(\005\022\025" +
      "\n\rcheck_in_date\030\002 \001(\t\022\026\n\016check_out_date\030" +
      "\003 \001(\t\022\022\n\ntotal_cost\030\004 \001(\002\022\020\n\010guest_id\030\005 " +
      "\001(\005\022\017\n\007room_id\030\006 \001(\005\"&\n\030DeleteReservatio" +
      "nRequest\022\n\n\002id\030\001 \001(\005\"5\n\017ReservationList\022" +
      "\"\n\014reservations\030\001 \003(\0132\014.Reservation\"a\n\004R" +
      "oom\022\n\n\002id\030\001 \001(\005\022\023\n\013room_number\030\002 \001(\t\022\014\n\004" +
      "type\030\003 \001(\t\022\027\n\017price_per_night\030\004 \001(\002\022\021\n\ta" +
      "vailable\030\005 \001(\010\"\034\n\016GetRoomRequest\022\n\n\002id\030\001" +
      " \001(\005\"b\n\021CreateRoomRequest\022\023\n\013room_number" +
      "\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022\027\n\017price_per_night\030" +
      "\003 \001(\002\022\021\n\tavailable\030\004 \001(\010\"n\n\021UpdateRoomRe" +
      "quest\022\n\n\002id\030\001 \001(\005\022\023\n\013room_number\030\002 \001(\t\022\014" +
      "\n\004type\030\003 \001(\t\022\027\n\017price_per_night\030\004 \001(\002\022\021\n" +
      "\tavailable\030\005 \001(\010\"\037\n\021DeleteRoomRequest\022\n\n" +
      "\002id\030\001 \001(\005\" \n\010RoomList\022\024\n\005rooms\030\001 \003(\0132\005.R" +
      "oom\"\007\n\005Empty2\276\005\n\014HotelService\022$\n\010GetGues" +
      "t\022\020.GetGuestRequest\032\006.Guest\022\"\n\014GetAllGue" +
      "sts\022\006.Empty\032\n.GuestList\022*\n\013CreateGuest\022\023" +
      ".CreateGuestRequest\032\006.Guest\022*\n\013UpdateGue" +
      "st\022\023.UpdateGuestRequest\032\006.Guest\022*\n\013Delet" +
      "eGuest\022\023.DeleteGuestRequest\032\006.Guest\0226\n\016G" +
      "etReservation\022\026.GetReservationRequest\032\014." +
      "Reservation\022.\n\022GetAllReservations\022\006.Empt" +
      "y\032\020.ReservationList\022<\n\021CreateReservation" +
      "\022\031.CreateReservationRequest\032\014.Reservatio" +
      "n\022<\n\021UpdateReservation\022\031.UpdateReservati" +
      "onRequest\032\014.Reservation\022<\n\021DeleteReserva" +
      "tion\022\031.DeleteReservationRequest\032\014.Reserv" +
      "ation\022!\n\007GetRoom\022\017.GetRoomRequest\032\005.Room" +
      "\022 \n\013GetAllRooms\022\006.Empty\032\t.RoomList\022\'\n\nCr" +
      "eateRoom\022\022.CreateRoomRequest\032\005.Room\022\'\n\nU" +
      "pdateRoom\022\022.UpdateRoomRequest\032\005.Room\022\'\n\n" +
      "DeleteRoom\022\022.DeleteRoomRequest\032\005.RoomB\022\n" +
      "\016com.grpc.stubsP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Guest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Guest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Guest_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "PhoneNumber", });
    internal_static_GetGuestRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GetGuestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetGuestRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CreateGuestRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CreateGuestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateGuestRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "PhoneNumber", });
    internal_static_UpdateGuestRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_UpdateGuestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateGuestRequest_descriptor,
        new java.lang.String[] { "Id", "FirstName", "LastName", "Email", "PhoneNumber", });
    internal_static_DeleteGuestRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_DeleteGuestRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteGuestRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_GuestList_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_GuestList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GuestList_descriptor,
        new java.lang.String[] { "Guests", });
    internal_static_Reservation_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Reservation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Reservation_descriptor,
        new java.lang.String[] { "Id", "CheckInDate", "CheckOutDate", "TotalCost", "GuestId", "RoomId", });
    internal_static_GetReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CreateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_CreateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateReservationRequest_descriptor,
        new java.lang.String[] { "CheckInDate", "CheckOutDate", "TotalCost", "GuestId", "RoomId", });
    internal_static_UpdateReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_UpdateReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateReservationRequest_descriptor,
        new java.lang.String[] { "Id", "CheckInDate", "CheckOutDate", "TotalCost", "GuestId", "RoomId", });
    internal_static_DeleteReservationRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_DeleteReservationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteReservationRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_ReservationList_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_ReservationList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ReservationList_descriptor,
        new java.lang.String[] { "Reservations", });
    internal_static_Room_descriptor =
      getDescriptor().getMessageTypes().get(12);
    internal_static_Room_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Room_descriptor,
        new java.lang.String[] { "Id", "RoomNumber", "Type", "PricePerNight", "Available", });
    internal_static_GetRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(13);
    internal_static_GetRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetRoomRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_CreateRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(14);
    internal_static_CreateRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateRoomRequest_descriptor,
        new java.lang.String[] { "RoomNumber", "Type", "PricePerNight", "Available", });
    internal_static_UpdateRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(15);
    internal_static_UpdateRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_UpdateRoomRequest_descriptor,
        new java.lang.String[] { "Id", "RoomNumber", "Type", "PricePerNight", "Available", });
    internal_static_DeleteRoomRequest_descriptor =
      getDescriptor().getMessageTypes().get(16);
    internal_static_DeleteRoomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DeleteRoomRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_RoomList_descriptor =
      getDescriptor().getMessageTypes().get(17);
    internal_static_RoomList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_RoomList_descriptor,
        new java.lang.String[] { "Rooms", });
    internal_static_Empty_descriptor =
      getDescriptor().getMessageTypes().get(18);
    internal_static_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
