// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.grpc.stubs;

public interface ReservationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Reservation)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string check_in_date = 2;</code>
   * @return The checkInDate.
   */
  java.lang.String getCheckInDate();
  /**
   * <code>string check_in_date = 2;</code>
   * @return The bytes for checkInDate.
   */
  com.google.protobuf.ByteString
      getCheckInDateBytes();

  /**
   * <code>string check_out_date = 3;</code>
   * @return The checkOutDate.
   */
  java.lang.String getCheckOutDate();
  /**
   * <code>string check_out_date = 3;</code>
   * @return The bytes for checkOutDate.
   */
  com.google.protobuf.ByteString
      getCheckOutDateBytes();

  /**
   * <code>float total_cost = 4;</code>
   * @return The totalCost.
   */
  float getTotalCost();

  /**
   * <code>int32 guest_id = 5;</code>
   * @return The guestId.
   */
  int getGuestId();

  /**
   * <code>int32 room_id = 6;</code>
   * @return The roomId.
   */
  int getRoomId();
}
