// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.grpc.stubs;

public interface RoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Room)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string room_number = 2;</code>
   * @return The roomNumber.
   */
  java.lang.String getRoomNumber();
  /**
   * <code>string room_number = 2;</code>
   * @return The bytes for roomNumber.
   */
  com.google.protobuf.ByteString
      getRoomNumberBytes();

  /**
   * <code>string type = 3;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 3;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>float price_per_night = 4;</code>
   * @return The pricePerNight.
   */
  float getPricePerNight();

  /**
   * <code>bool available = 5;</code>
   * @return The available.
   */
  boolean getAvailable();
}
