// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package com.grpc.stubs;

public interface RoomListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RoomList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  java.util.List<com.grpc.stubs.Room> 
      getRoomsList();
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  com.grpc.stubs.Room getRooms(int index);
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  int getRoomsCount();
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  java.util.List<? extends com.grpc.stubs.RoomOrBuilder> 
      getRoomsOrBuilderList();
  /**
   * <code>repeated .Room rooms = 1;</code>
   */
  com.grpc.stubs.RoomOrBuilder getRoomsOrBuilder(
      int index);
}
